name: Generate Fonts

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Download latest version of Cascadia
      run: curl -L https://github.com/microsoft/cascadia-code/releases/latest/download/Cascadia.ttf  --output Cascadia.ttf
    - name: Install FontForge
      run: |
        sudo add-apt-repository ppa:fontforge/fontforge -y -u;
        sudo apt-get install fontforge -y;
    - name: Download Font Patcher
      run: curl -L https://raw.githubusercontent.com/ryanoasis/nerd-fonts/master/font-patcher --output font-patcher
#     - name: Patch Font Patcher for Ligature Glyphs
#       run: patch -u font-patcher < font-patcher.patch
    - name: Download source fonts
      run: |
        chmod +x download-source-fonts.sh
        ./download-source-fonts.sh
    - name: Install PIP
      run: sudo apt install python-pip -y
    - name: Install configparser
      run: pip install configparser
    - name: Build Powerline
      run: |
        fontforge -script font-patcher --careful --powerline --no-progressbars --mono Cascadia.ttf | tee process.log
        git describe --always | xargs fontforge rename-font --input Cascadia*\ Nerd\ Font\ Mono.ttf \
                                                            --output "Delugia Nerd Font.ttf" \
                                                            --name "Delugia Nerd Font" \
                                                            --version
    - name: Build Complete
      run: |
        fontforge -script font-patcher --careful -c --no-progressbars --mono Cascadia.ttf | tee process_full.log
        git describe --always | xargs fontforge rename-font --input Cascadia*\ Nerd\ Font\ Complete\ Mono.ttf \
                                                            --output "Delugia Nerd Font Complete.ttf" \
                                                            --name "Delugia Nerd Font" \
                                                            --version
    - name: Check for preexisting glyphs
      run: |
        grep 'Found existing' process*.log
    - uses: actions/upload-artifact@master
      with:
        name: Delugia Nerd Font Powerline
        path: "Delugia Nerd Font.ttf"
    - uses: actions/upload-artifact@master
      with:
        name: Delugia Nerd Font Complete
        path: "Delugia Nerd Font Complete.ttf"
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          Delugia Nerd Font.ttf
          Delugia Nerd Font Complete.ttf
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
